### ISSUE TITLE
Aliased action result not broadcast

### ISSUE THREAD

**Issue by joshuef** [hardchor/electron-redux#106]
As per the docs: 
> you can quite easily create actions that are are only being executed in the main process, and the result of which is being broadcast to the renderer processes

1. create an aliased action
2. call `function` as payload
3. `function` does stuff, and returns a `payload`
4. according to docs, _this_ result should be broadcast as the action in renderer processes.
5. It is not. Renderer processes only see `ALIASED ACTION`. 

**Expected behavior**
Renderer process stores are updated.

----

Right now I get around this triggering other actions as part of my aliased action. And so updating the store all-round. But if broadcasting the result is intended behaviour, then it would be great to see this fixed.

Happy to work on a PR, just not sure if the doc description is correct, or if that's not actually intended behaviour.

**Comment by hunterlester** [comment]
According to [docs](https://github.com/hardchor/electron-redux#aliased-actions-main-process), aliased actions are for executing an action in the main process and have the result be broadcast to the renderer processes.
In my case, in issue #12, it seems like the issue was that I was calling an aliased action in a renderer process. Removing the aliased action wrapper from the action creator, produces the expected outcome.

**Comment by hardchor** [comment]
Hey @joshuef! I looked through the attached issue, and it sounds like it was just an issue with how you'd executed the aliased action?

Feel free to reopen if anything is unclear.
