### ISSUE TITLE
[Discussion] - Does ipcRenderer.invoke() provide any way to avoid ipc.sendSync()?

### ISSUE THREAD

**Issue by Slapbox** [hardchor/electron-redux#137]
`Electron@7` includes a new method [ipcRenderer.invoke()](https://electronjs.org/docs/api/ipc-renderer#ipcrendererinvokechannel-args)

I doubt this opens any possibility to avoid reliance on [sendSync](https://electronjs.org/docs/api/ipc-renderer#ipcrenderersendsyncchannel-args) which is currently used, but I wanted to mention this new method to be sure that there wasn't some cool, higher performance method that could be devised with this.

@hardchor, am I right to think think this will not provide any way to boost the performance of `electron-redux`? Performance is quite good, but I imagine that if there were a way to ditch `sendSync` that performance could be boosted quite a lot. I don't imagine that there's a way though.

**Comment by hardchor** [comment]
Hey @Slapbox :)

The good news is we're not using `sendSync` (but `send`), so we're not blocking the renderer process.

I can't see any immediate advantage to using `invoke` (unless maybe for the initial renderer store setup), since all our actions are being fanned out by the main process to the renderer processes and the renderer itself wouldn't need an immediate response from the main store in a normal scenario (see https://cloud.githubusercontent.com/assets/307162/20675737/385ce59e-b585-11e6-947e-3867e77c783d.png).

Happy to discuss if you can think of another scenario!

**Comment by hardchor** [comment]
Just for reference: https://github.com/hardchor/electron-redux/blob/master/packages/electron-redux/src/middleware/forwardToMain.js#L16

**Comment by Slapbox** [comment]
@hardchor thanks for the update! I had really thought this was using `sendSync`, but apparently it never has. I don't know why I thought that, but I appreciate your response! 

I didn't anticipate any benefit to `invoke` in any event, but I figured I'd bring it up for discussion just to be sure.

Thank you for sharing Electron Redux, it's really phenomenal!
