### ISSUE TITLE
Dispatch actions are now async

### ISSUE THREAD

**Issue by sallar** [hardchor/electron-redux#31]
Hi,

I have been using this module for past few days, 
This module makes actions async, so when I dispatch an action, it's not guaranteed to be sync anymore. So: 

``` js
dispatch(setCurrentArchive(info.id));
console.log(getState());
```

The `console.log` will happen **before** the dispatch. The reason is the `forwardToMain` middleware does not call `next(action)` so the order is not guaranteed anymore.

While [redux-electron-store](https://github.com/samiskin/redux-electron-store) uses **enhancers** to dispatch actions between threads, this module uses middlewares which I think is not a good idea. 

What do you think?

**Comment by hardchor** [comment]
Hey,

Sorry for the late reply, just got back from a longer holiday.

You are completely right, actions dispatched are now asynchronous. This is because they are being dispatched via IPC (which is inherently async). The reason why `forwardToMain` forwards any (except local) actions to main and stops them from being propagated locally.

I'd be surprised if `redux-electron-store` were to work any differently (not sure what exactly they're doing).

**Comment by sallar** [comment]
@hardchor Thanks! It's ok. 
I ended up using theirs, as it keeps the actions sync and doesn't actually modify the action itself. How they do it is they forward it regardless of the action itself (they don't wait on the answer). Here's how I set that up:
https://github.com/buttercup/buttercup/blob/master/src/shared/store/configure-store.js#L39

Thanks!

**Comment by burkhardr** [comment]
@sallar And how do they avoid duplicate actions on the originating window? That was the only reason really why I'm doing it this way.

**Comment by hardchor** [comment]
Closing this
