### ISSUE TITLE
❓ Discuss: Do we need to make actions synchronous again?

### ISSUE THREAD

**Issue by hardchor** [hardchor/electron-redux#52]
https://github.com/hardchor/electron-redux/issues/31 raised the point that actions fired are now async. This is a technical restriction of IPC and the approach we've chosen to send any actions to the main store first before fanning them out to the renderer store(s).

Whilst actions do therefore become async, they should still stay in order (so won't have any effect on the redux state itself).

We could put in some effort to apply actions originating from the same process immediately, and then filter them out once they get replayed by the main store (to avoid duplicate actions), but that would add some complexity, so I guess the question is:

**Has the asynchronicity of actions in `electron-redux` caused you any problems so far?** (bonus points for comments). Use 👍 or 👎

**Comment by eric-burel** [comment]
Hi, it seems to break actions order sometimes, which in turns breaks redux-saga behaviour. I'm investigating.
The issue is that applying `meta:"local"` (I guess it makes actions synchronous again ?) is not easy when using 3rd party libs, like `react-redux-router`.

**Comment by eric-burel** [comment]
Hi,
This will be necessary for redux-saga and thunk to work correctly. Indeed, action reducing order is not guaranteed anymore. Here is a small example:
```
fetchData // local action
fetchDataSuccess // global action, everybody enjoy the result
manipulateData // local again
manipulateDataSuccess // global
```
will actually run in this order 
```
fetchData
manipulateData // ERROR : I haven't receive my success action yet, so my state isn't correctly defined
fetchDataSucces
manipulateDataSuccess
```
Local actions will be fired before non local action, which can be annoying in certain asyncrhonous process.

**Comment by hardchor** [comment]
@eric-burel Things like data fetching should (ideally) only happen on the main thread, hence the `aliasedAction` helper. Does this work for you?

**Comment by LucaColonnello** [comment]
I was trying to build an Electron app and wanted to try out redux-saga with electron-redux.
This is something that would be really helpful, since an application like this is more likely to have all the business logic in the main process, which is what this package let us doing. redux-saga is the perfect fit for those cases.

If I mount all the sagas in the main process, it'd be ideal to have the util having a dispatch without wait mode, with just IPC broadcast. Is there any way to do it with the current implementation?

**Comment by CharlieHess** [comment]
We've been using this in combination with `redux-observable`, and in that case the current behavior is a perfect fit. It's fairly agnostic to the order of actions, for two reasons:

1. `redux-observable` lets you pick actions off the store by type, similar to an event bus or a pub/sub model
1. Observable operators let you share (aka "publish") subscriptions, so if you _ever_ received an action of a certain type you can save that result for later

We explicitly switched from `redux-electron-store` because there is a non-trivial cost to its process synchronization strategy. Tread carefully!

**Comment by hardchor** [comment]
@LucaColonnello Running sagas (or anything that produces side effects) in the main thread is the right approach, and that's what aliased actions were created for. I'm not entirely sure what you mean by "wait mode"?

@CharlieHess I wrote this package because their strategy seemed unnecessarily complicated. Unfortunately, it comes with the aforementioned limitations.

**Comment by LucaColonnello** [comment]
@hardchor I meant without the util to require a function to run. If I can dispatch an action that is only going to main, then I'll mount all the sagas in the main, which will be the only sagas runner!

**Comment by hardchor** [comment]
@LucaColonnello As just discussed on slack (and for the benefit for everyone else), [aliased actions](https://github.com/hardchor/electron-redux#aliased-actions-main-process) is what you're looking for!

**Comment by LucaColonnello** [comment]
@hardchor Very cool!!!!! :) Thanks!

**Comment by hardchor** [comment]
Closing this for now

**Comment by matt-way** [comment]
I was keen to use this library, porting some existing redux stuff to multithreaded, but didn't realise the actions are no longer sync. Even inside a simple thunk like this...

```
dispatch(something())
dispatch(somethingElse())
```
the order isn't guaranteed, which breaks my existing setup. One of the great things about redux is that it has synchronous flow. Now I'm unable to chain actions.

**Comment by eric-burel** [comment]
@matt-way Hi, redux being totally synchrone is more one of its limitations than a feature. You will need to invent your own patterns to solve this.
Possible solution  is to dispatch arrays. You then simply need a middleware very similar to thunk that handles arrays of actions instead of actions only (I think that's even a classic example of redux middlware, there might be a lib for this).
So the pattern for chained action would be:

1. Generate an array of actions (taking conditions etc. into account)
2. Dispatch the array
